const convertFontIcon = (icon = "la ") => {
  switch (icon.replace("la ", "")) {
    case "la-line-chart":
    case "activity":
      return "activity";
    case "la-exclamation-circle":
    case "alert-circle":
      return "alert-circle";
    case "la-exclamation-triangle":
    case "alert-triangle":
      return "alert-triangle";
    case "la-align-center":
    case "align-center":
      return "align-center";
    case "la-align-justify":
    case "align-justify":
      return "align-justify";
    case "la-align-left":
    case "align-left":
      return "align-left";
    case "la-align-right":
    case "align-right":
      return "align-right";
    case "la-anchor":
    case "anchor":
      return "anchor";
    case "la-arrow-circle-down":
    case "arrow-down-circle":
      return "arrow-down-circle";
    case "la-arrow-circle-up":
    case "arrow-up-circle":
      return "arrow-up-circle";
    case "la-arrow-circle-left":
    case "arrow-left-circle":
      return "arrow-left-circle";
    case "la-arrow-circle-right":
    case "arrow-right-circle":
      return "arrow-right-circle";
    case "la-arrow-down":
    case "arrow-down":
      return "arrow-down";
    case "la-arrow-up":
    case "arrow-up":
      return "arrow-up";
    case "la-arrow-left":
    case "arrow-left":
      return "arrow-left";
    case "la-arrow-right":
    case "arrow-right":
      return "arrow-right";
    case "la-at":
    case "at-sign":
      return "at-sign";
    case "la-bar-chart":
    case "bar-chart":
      return "bar-chart";
    case "la-battery-three-quarters":
    case "battery-charging":
      return "battery-charging";
    case "la-battery-0":
    case "battery":
      return "battery";
    case "la-bell-slash":
    case "la-bell-slash-o":
    case "bell-off":
      return "bell-off";
    case "la-bell":
    case "la-bell-o":
    case "bell":
      return "bell";
    case "la-bold":
    case "bold":
      return "bold";
    case "la-book":
    case "book":
      return "book";
    case "la-bookmark":
    case "la-bookmark-o":
    case "bookmark":
      return "bookmark";
    case "la-briefcase":
    case "briefcase":
      return "briefcase";
    case "la-calendar-check-o":
    case "la-calendar-o":
    case "la-calendar":
    case "calendar":
      return "calendar";
    case "la-camera-retro":
    case "la-camera":
    case "camera":
      return "camera";
    case "la-check-circle":
    case "la-check-circle-o":
    case "check-circle":
      return "check-circle";
    case "la-check-square":
    case "la-check-square-o":
    case "check-square":
      return "check-square";
    case "la-check":
    case "check":
      return "check";
    case "la-angle-down":
    case "chevron-down":
      return "chevron-down";
    case "la-angle-up":
    case "chevron-up":
      return "chevron-up";
    case "la-angle-left":
    case "chevron-left":
      return "chevron-left";
    case "la-angle-right":
    case "chevron-right":
      return "chevron-right";
    case "la-angle-double-down":
    case "chevrons-down":
      return "chevrons-down";
    case "la-angle-double-up":
    case "chevrons-up":
      return "chevrons-up";
    case "la-angle-double-left":
    case "chevrons-left":
      return "chevrons-left";
    case "la-angle-double-right":
    case "chevrons-right":
      return "chevrons-right";
    case "la-chrome":
    case "chrome":
      return "chrome";
    case "la-circle":
    case "circle":
      return "circle";
    case "la-archive":
    case "la-clipboard":
    case "clipboard":
      return "clipboard";
    case "la-clock-o":
    case "clock":
      return "clock";
    case "la-cloud":
    case "cloud":
      return "cloud";
    case "la-code":
    case "code":
      return "code";
    case "la-codepen":
    case "codepen":
      return "codepen";
    case "la-compass":
    case "compass":
      return "compass";
    case "la-copy":
    case "copy":
      return "copy";
    case "la-credit-card":
    case "credit-card":
      return "credit-card";
    case "la-crop":
    case "crop":
      return "crop";
    case "la-crosshairs":
    case "crosshair":
      return "crosshair";
    case "la-database":
    case "database":
      return "database";
    case "la-dot-circle-o":
    case "disc":
      return "disc";
    case "la-cloud-download":
    case "download-cloud":
      return "download-cloud";
    case "la-edit":
    case "edit":
      return "edit";
    case "la-external-link":
    case "external-link":
      return "external-link";
    case "la-eye-slash":
    case "eye-off":
      return "eye-off";
    case "la-eye":
    case "eye":
      return "eye";
    case "la-facebook":
    case "la-facebook-f":
    case "la-facebook-official":
    case "la-facebook-square":
    case "facebook":
      return "facebook";
    case "la-forward":
    case "fast-forward":
      return "fast-forward";
    case "la-file-text":
    case "la-file-text-o":
    case "file-text":
      return "file-text";
    case "la-file":
    case "la-file-o":
    case "file":
      return "file";
    case "la-film":
    case "film":
      return "film";
    case "la-filter":
    case "filter":
      return "filter";
    case "la-flag":
    case "la-flag-o":
    case "flag":
      return "flag";
    case "la-folder":
    case "la-folder-o":
    case "folder":
      return "folder";
    case "la-gift":
    case "gift":
      return "gift";
    case "la-github":
    case "la-github-alt":
    case "la-github-square":
    case "github":
      return "github";
    case "la-globe":
    case "globe":
      return "globe";
    case "la-headphones":
    case "headphones":
      return "headphones";
    case "la-heart":
    case "heart":
      return "heart";
    case "la-question-circle":
    case "help-circle":
      return "help-circle";
    case "la-home":
    case "home":
      return "home";
    case "la-image":
    case "image":
      return "image";
    case "la-image":
    case "image":
      return "image";
    case "la-inbox":
    case "inbox":
      return "inbox";
    case "la-info":
    case "la-info-circle":
    case "info":
      return "info";
    case "la-instagram":
    case "instagram":
      return "instagram";
    case "la-italic":
    case "italic":
      return "italic";
    case "la-database":
    case "layers":
      return "layers";
    case "la-columns":
    case "layout":
      return "layout";
    case "la-life-buoy":
    case "life-buoy":
      return "life-buoy";
    case "la-link":
    case "link":
      return "link";
    case "la-list":
    case "la-list-alt":
    case "la-list-ol":
    case "la-list-ul":
    case "list":
      return "list";
    case "la-spinner":
    case "loader":
      return "loader";
    case "la-lock":
    case "lock":
      return "lock";
    case "la-envelope":
    case "la-envelope-o":
    case "la-envelope-square":
    case "mail":
      return "mail";
    case "la-map-marker":
    case "la-map-pin":
    case "map-pin":
      return "map-pin";
    case "la-map":
    case "map":
      return "map";
    case "la-expand":
    case "maximize-2":
      return "maximize-2";
    case "la-arrows-alt":
    case "maximize":
      return "maximize";
    case "la-bars":
    case "la-navicon":
    case "menu":
      return "menu";
    case "la-comment":
    case "la-comment-o":
    case "la-commenting":
    case "la-commenting-o":
    case "la-comments":
    case "la-comments-o":
    case "message-square":
      return "message-square";
    case "la-microphone-slash":
    case "mic-off":
      return "mic-off";
    case "la-la-microphone":
    case "mic":
      return "mic";
    case "la-compress":
    case "minimize-2":
      return "minimize-2";
    case "la-link":
    case "link":
      return "link";
    case "la-minus-circle":
    case "minus-circle":
      return "minus-circle";
    case "la-minus-square":
    case "minus-square":
      return "minus-square";
    case "la-minus":
    case "minus":
      return "minus";
    case "la-desktop":
    case "monitor":
      return "monitor";
    case "la-moon-o":
    case "moon":
      return "moon";
    case "la-ellipsis-h":
    case "more-horizontal":
      return "more-horizontal";
    case "la-ellipsis-v":
    case "more-vertical":
      return "more-vertical";
    case "la-cube":
    case "package":
      return "package";
    case "la-paperclip":
    case "paperclip":
      return "paperclip";
    case "la-music":
    case "music":
      return "music";
    case "la-pause":
    case "pause":
      return "pause";
    case "la-phone":
    case "la-phone-square":
    case "phone":
      return "phone";
    case "la-pie-chart":
    case "piechart":
      return "piechart";
    case "la-play-circle":
    case "la-play-circle-o":
    case "play-circle":
      return "play-circle";
    case "la-play":
    case "play":
      return "play";
    case "la-plus-circle":
    case "plus-circle":
      return "plus-circle";
    case "la-plus-square":
    case "plus-square":
      return "plus-square";
    case "la-plus":
    case "plus":
      return "plus";
    case "la-get-pocket":
    case "pocket":
      return "pocket";
    case "la-power-off":
    case "power":
      return "power";
    case "la-print":
    case "printer":
      return "printer";
    case "la-refresh":
    case "refresh-cw":
      return "refresh-cw";
    case "la-repeat":
    case "repeat":
      return "repeat";
    case "la-backward":
    case "rewind":
      return "rewind";
    case "la-rotate-left":
    case "rotate-ccw":
      return "rotate-ccw";
    case "la-rotate-right":
    case "rotate-cw":
      return "rotate-cw";
    case "la-rss":
    case "la-rss-square":
    case "rss":
      return "rss";
    case "la-save":
    case "save":
      return "save";
    case "la-scissors":
    case "la-cut":
    case "scissors":
      return "scissors";
    case "la-search":
    case "la-search-plus":
    case "search":
      return "search";
    case "la-send":
    case "la-send-o":
    case "la-paper-plane-o":
    case "send":
      return "send";
    case "la-server":
    case "server":
      return "server";
    case "la-wrench":
    case "la-cog":
    case "la-cogs":
    case "settings":
      return "settings";
    case "la-share":
    case "la-share-square":
    case "la-share-square-o":
    case "share-2":
      return "share-2";
    case "la-share-alt":
    case "la-share-alt-square":
    case "share":
      return "share";
    case "la-shield":
    case "shield":
      return "shield";
    case "la-shopping-cart":
    case "shopping-cart":
      return "shopping-cart";
    case "la-step-backward":
    case "skip-back":
      return "skip-back";
    case "la-step-forward":
    case "skip-forward":
      return "skip-forward";
    case "la-slack":
    case "slack":
      return "slack";
    case "la-sliders":
    case "sliders":
      return "sliders";
    case "la-mobile":
    case "la-mobile-phone":
    case "smartphone":
      return "smartphone";
    case "la-star":
    case "la-star-o":
    case "star":
      return "star";
    case "la-stop":
    case "stop-circle":
      return "stop-circle";
    case "la-sun-o":
    case "sun":
      return "sun";
    case "la-tablet":
    case "tablet":
      return "tablet";
    case "la-tag":
    case "la-tags":
    case "tag":
      return "tag";
    case "la-bullseye":
    case "target":
      return "target";
    case "la-terminal":
    case "terminal":
      return "terminal";
    case "la-thumbs-down":
    case "la-thumbs-o-down":
    case "thumbs-down":
      return "thumbs-down";
    case "la-thumbs-up":
    case "la-thumbs-o-up":
    case "thumbs-up":
      return "thumbs-up";
    case "la-toggle-off":
    case "toggle-left":
      return "toggle-left";
    case "la-toggle-on":
    case "toggle-right":
      return "toggle-right";
    case "la-trash":
    case "la-trash-o":
    case "trash-2":
      return "trash-2";
    case "la-flash":
    case "la-bolt":
    case "trending-down":
      return "trending-down";
    case "la-truck":
    case "truck":
      return "truck";
    case "la-pause":
    case "pause":
      return "pause";
    case "la-tv":
    case "tv":
      return "tv";
    case "la-twitter":
    case "la-twitter-square":
    case "twitter":
      return "twitter";
    case "la-umbrella":
    case "umbrella":
      return "umbrella";
    case "la-underline":
    case "underline":
      return "underline";
    case "la-unlock":
    case "la-unlock-alt":
    case "unlock":
      return "unlock";
    case "la-cloud-upload":
    case "upload-cloud":
      return "upload-cloud";
    case "la-upload":
    case "upload":
      return "upload";
    case "la-user-plus":
    case "user-plus":
      return "user-plus";
    case "la-user-times":
    case "user-x":
      return "user-x";
    case "la-user":
    case "user":
      return "user";
    case "la-users":
    case "users":
      return "users";
    case "la-video-camera":
    case "video":
      return "video";
    case "la-volume-down":
    case "volume-1":
      return "volume-1";
    case "la-volume-up":
    case "volume-2":
      return "volume-2";
    case "la-volume-off":
    case "volume-x":
      return "volume-x";
    case "la-wifi":
    case "wifi":
      return "wifi";
    case "la-times-circle":
    case "la-times-circle-o":
    case "la-close":
    case "x-circle":
      return "x-circle";
    case "la-times":
    case "la-times-o":
    case "x":
      return "x";
    case "la-youtube-play":
    case "youtube":
      return "youtube";
    case "la-search-plus":
    case "zoom-in":
      return "zoom-in";
    case "la-search-minus":
    case "zoom-out":
      return "zoom-out";
    default:
      return false;
  }
};

export default convertFontIcon;
