export const FIREBASE = "FIREBASE";
export const LOADING = "LOADING";
export const LOADING_LISTING_DETAIL = "LOADING_LISTING_DETAIL";
export const LOADING_REVIEW = "LOADING_REVIEW";
export const SCROLL_TO = "SCROLL_TO";
export const REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
export const HOME_REQUEST_TIMEOUT = "HOME_REQUEST_TIMEOUT";
export const ARTICLE_REQUEST_TIMEOUT = "ARTICLE_REQUEST_TIMEOUT";
export const LISTING_REQUEST_TIMEOUT = "LISTING_REQUEST_TIMEOUT";
export const LISTING_SEARCH_REQUEST_TIMEOUT = "LISTING_SEARCH_REQUEST_TIMEOUT";
export const EVENT_SEARCH_REQUEST_TIMEOUT = "EVENT_SEARCH_REQUEST_TIMEOUT";
export const EVENT_REQUEST_TIMEOUT = "EVENT_REQUEST_TIMEOUT";
export const LISTING_DETAIL_DES_REQUEST_TIMEOUT =
  "LISTING_DETAIL_DES_REQUEST_TIMEOUT";
export const LISTING_DETAIL_PHOTOS_REQUEST_TIMEOUT =
  "LISTING_DETAIL_PHOTOS_REQUEST_TIMEOUT";
export const LISTING_DETAIL_VID_REQUEST_TIMEOUT =
  "LISTING_DETAIL_VID_REQUEST_TIMEOUT";
export const LISTING_DETAIL_LIST_REQUEST_TIMEOUT =
  "LISTING_DETAIL_LIST_REQUEST_TIMEOUT";
export const LISTING_DETAIL_REVIEWS_REQUEST_TIMEOUT =
  "LISTING_DETAIL_REVIEWS_REQUEST_TIMEOUT";
export const LISTING_DETAIL_EVENT_REQUEST_TIMEOUT =
  "LISTING_DETAIL_EVENT_REQUEST_TIMEOUT";
export const LISTING_DETAIL_SIDEBAR_REQUEST_TIMEOUT =
  "LISTING_DETAIL_SIDEBAR_REQUEST_TIMEOUT";
export const MENU_REQUEST_TIMEOUT = "MENU_REQUEST_TIMEOUT";

export const NEAR_BY_FOCUS = "NEAR_BY_FOCUS";

export const GET_TAB_NAVIGATOR = "GET_TAB_NAVIGATOR";
export const GET_STACK_NAVIGATOR = "GET_STACK_NAVIGATOR";

export const GET_TRANSLATIONS = "GET_TRANSLATIONS";
export const GET_LISTINGS = "GET_LISTINGS";
export const GET_LISTINGS_LOADMORE = "GET_LISTINGS_LOADMORE";
export const GET_LISTING_SEARCH_RESULTS = "GET_LISTING_SEARCH_RESULTS";
export const GET_LISTING_SEARCH_RESULTS_LOADMORE =
  "GET_LISTING_SEARCH_RESULTS_LOADMORE";
export const GET_LISTING_BY_CAT = "GET_LISTING_BY_CAT";
export const GET_LISTING_BY_CAT_LOADMORE = "GET_LISTING_BY_CAT_LOADMORE";
export const GET_LISTING_NEARBY = "GET_LISTING_NEARBY";
export const GET_HOME_SCREEN = "GET_HOME_SCREEN";
export const GET_LISTING_FILTERS = "GET_LISTING_FILTERS";
export const PUT_NEW_TAG_LISTING_FILTERS = "PUT_NEW_TAG_LISTING_FILTERS";
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const RESET_SELECTED_CATEGORY_LIST = "RESET_SELECTED_CATEGORY_LIST";
export const RESET_SELECTED_LOCATION_LIST = "RESET_SELECTED_LOCATION_LIST";
export const CHANGE_CATEGORY_LIST = "CHANGE_CATEGORY_LIST";
export const CHANGE_LOCATION_LIST = "CHANGE_LOCATION_LIST";
export const GET_LOCATION = "GET_LOCATION";
export const GET_LISTING_BOX_CUSTOM = "GET_LISTING_BOX_CUSTOM";
export const GET_LISTING_BOX_CUSTOM_ALL = "GET_LISTING_BOX_CUSTOM_ALL";

export const GET_LISTING_DETAIL = "GET_LISTING_DETAIL";
export const RESET_LISTING_DETAIL = "RESET_LISTING_DETAIL";
export const GET_LISTING_DESTINATION = "GET_LISTING_DESTINATION";
export const GET_LISTING_DESTINATION_ALL = "GET_LISTING_DESTINATION_ALL";
export const GET_LISTING_LIST_FEATURE = "GET_LISTING_LIST_FEATURE";
export const GET_LISTING_LIST_FEATURE_ALL = "GET_LISTING_LIST_FEATURE_ALL";
export const GET_LISTING_PHOTOS = "GET_LISTING_PHOTOS";
export const GET_LISTING_PHOTOS_ALL = "GET_LISTING_PHOTOS_ALL";
export const GET_LISTING_REVIEWS = "GET_LISTING_REVIEWS";
export const GET_LISTING_REVIEWS_ALL = "GET_LISTING_REVIEWS_ALL";
export const GET_LISTING_REVIEWS_ALL_LOADMORE =
  "GET_LISTING_REVIEWS_ALL_LOADMORE";
export const GET_LISTING_EVENTS = "GET_LISTING_EVENTS";
export const GET_LISTING_EVENTS_ALL = "GET_LISTING_EVENTS_ALL";
export const GET_LISTING_VIDEOS = "GET_LISTING_VIDEOS";
export const GET_LISTING_VIDEOS_ALL = "GET_LISTING_VIDEOS_ALL";
export const GET_LISTING_DETAIL_NAV = "GET_LISTING_DETAIL_NAV";
export const CHANGE_LISTING_DETAIL_NAV = "CHANGE_LISTING_DETAIL_NAV";
export const GET_COMMENT_IN_REVIEWS = "GET_COMMENT_IN_REVIEWS";
export const POST_COMMENT_IN_REVIEWS = "POST_COMMENT_IN_REVIEWS";
export const EDIT_COMMENT_IN_REVIEWS = "EDIT_COMMENT_IN_REVIEWS";
export const DELETE_COMMENT_IN_REVIEWS = "DELETE_COMMENT_IN_REVIEWS";
export const GET_LISTING_SIDEBAR = "GET_LISTING_SIDEBAR";
export const GET_REPORT_FORM = "GET_REPORT_FORM";
export const GET_REPORT_MESSAGE = "GET_REPORT_MESSAGE";

export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL";
export const GET_EVENTS_LOADMORE = "GET_EVENTS_LOADMORE";
export const GET_EVENT_DISCUSSION = "GET_EVENT_DISCUSSION";
export const GET_EVENT_DISCUSSION_LATEST = "GET_EVENT_DISCUSSION_LATEST";
export const GET_EVENT_DISCUSSION_LOADMORE = "GET_EVENT_DISCUSSION_LOADMORE";
export const GET_COMMENT_DISCUSSION_EVENT = "GET_COMMENT_DISCUSSION_EVENT";
export const POST_COMMENT_DISCUSSION_EVENT = "POST_COMMENT_DISCUSSION_EVENT";
export const EDIT_COMMENT_DISCUSSION_EVENT = "EDIT_COMMENT_DISCUSSION_EVENT";
export const DELETE_COMMENT_DISCUSSION_EVENT =
  "DELETE_COMMENT_DISCUSSION_EVENT";
export const POST_EVENT_DISCUSSION = "POST_EVENT_DISCUSSION";
export const DELETE_EVENT_DISCUSSION = "DELETE_EVENT_DISCUSSION";
export const EDIT_EVENT_DISCUSSION = "EDIT_EVENT_DISCUSSION";
export const LIKE_EVENT_DISCUSSION = "LIKE_EVENT_DISCUSSION";
export const SHARE_EVENT_DISCUSSION = "SHARE_EVENT_DISCUSSION";
export const RESET_EVENT_DISCUSSION = "RESET_EVENT_DISCUSSION";
export const RESET_CMT_EVENT_DISCUSSION = "RESET_CMT_EVENT_DISCUSSION";
export const ACTION_EVENT_DISCUSSION_MESSAGE =
  "ACTION_EVENT_DISCUSSION_MESSAGE";

export const GET_EVENT_SEARCH_RESULTS = "GET_EVENT_SEARCH_RESULTS";
export const GET_EVENT_SEARCH_RESULTS_LOADMORE =
  "GET_EVENT_SEARCH_RESULTS_LOADMORE";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_LOADMORE = "GET_ARTICLES_LOADMORE";
export const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL";

export const GET_PAGE = "GET_PAGE";
export const GET_SETTINGS = "GET_SETTINGS";

export const IS_POPUP_LOGIN = "IS_POPUP_LOGIN";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_MY_FAVORITES = "GET_MY_FAVORITES";
export const TOGGLE_MY_FAVORITES = "TOGGLE_MY_FAVORITES";
export const RESET_MY_FAVORITES = "RESET_MY_FAVORITES";
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const POST_MY_PROFILE = "POST_MY_PROFILE";
export const POST_MY_PROFILE_ERROR = "POST_MY_PROFILE_ERROR";
export const GET_SHORT_PROFILE = "GET_SHORT_PROFILE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const ADD_LISTING_DETAIL_FAVORITES = "ADD_LISTING_DETAIL_FAVORITES";
export const GET_ACCOUNT_NAV = "GET_ACCOUNT_NAV";
export const GET_PROFILE_FORM = "GET_PROFILE_FORM";
export const GET_MY_LISTINGS = "GET_MY_LISTINGS";
export const GET_MY_LISTINGS_LOADMORE = "GET_MY_LISTINGS_LOADMORE";
export const GET_MY_LISTING_ERROR = "GET_MY_LISTING_ERROR";
export const GET_LISTING_STATUS = "GET_LISTING_STATUS";
export const GET_EVENT_STATUS = "GET_EVENT_STATUS";
export const GET_POST_TYPES = "GET_POST_TYPES";
export const GET_MY_EVENTS = "GET_MY_EVENTS";
export const GET_MY_EVENTS_LOADMORE = "GET_MY_EVENTS_LOADMORE";
export const GET_MY_EVENT_ERROR = "GET_MY_EVENT_ERROR";
export const GET_MY_NOTIFICATIONS = "GET_MY_NOTIFICATIONS";
export const GET_MY_NOTIFICATIONS_LOADMORE = "GET_MY_NOTIFICATIONS_LOADMORE";
export const GET_MY_NOTIFICATION_ERROR = "GET_MY_NOTIFICATION_ERROR";
export const DELETE_MY_NOTIFICATION = "DELETE_MY_NOTIFICATION";
export const DELETE_MY_NOTIFICATION_ERROR = "DELETE_MY_NOTIFICATION_ERROR";
export const GET_MESSAGE_LIST = "GET_MESSAGE_LIST";
export const GET_MESSAGE_CHAT = "GET_MESSAGE_CHAT";
export const GET_MESSAGE_CHAT_LOADMORE = "GET_MESSAGE_CHAT_LOADMORE";
export const PUT_MESSAGE_CHAT = "PUT_MESSAGE_CHAT";
export const PUT_MESSAGE_CHAT_LISTENER = "PUT_MESSAGE_CHAT_LISTENER";
export const DELETE_MESSAGE_CHAT = "DELETE_MESSAGE_CHAT";
export const EDIT_MESSAGE_CHAT = "EDIT_MESSAGE_CHAT";
export const RESET_MESSAGE_CHAT = "RESET_MESSAGE_CHAT";
export const WRITING_MESSAGE_CHAT = "WRITING_MESSAGE_CHAT";
export const GET_MESSAGE_NEW_COUNT = "GET_MESSAGE_NEW_COUNT";
export const GET_CURRENT_SEND_MESSAGE_SCREEN =
  "GET_CURRENT_SEND_MESSAGE_SCREEN";
export const GET_SIGNUP_FORM = "GET_SIGNUP_FORM";
export const SIGNUP = "SIGNUP";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const GET_COUNT_MESSAGES = "GET_COUNT_MESSAGES";
export const GET_COUNT_NOTIFICATIONS = "GET_COUNT_NOTIFICATIONS";
export const GET_COUNT_NOTIFICATIONS_REALTIMEFAKER =
  "GET_COUNT_NOTIFICATIONS_REALTIMEFAKER";
export const SEARCH_USERS = "SEARCH_USERS";
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR";
export const GET_USER = "GET_USER";
export const GET_USERS_FROM_FIREBASE = "GET_USERS_FROM_FIREBASE";
export const GET_USERS_FROM_FIREBASE_LOADING =
  "GET_USERS_FROM_FIREBASE_LOADING";
export const GET_USERS_FROM_FIREBASE_ERROR = "GET_USERS_FROM_FIREBASE_ERROR";
export const GET_KEY_FIREBASE = "GET_KEY_FIREBASE";
export const GET_KEY_FIREBASE2 = "GET_KEY_FIREBASE2";
export const USER_CONNECTION = "USER_CONNECTION";
export const POST_USER_CONNECTION = "POST_USER_CONNECTION";
export const GET_DEVICE_TOKEN = "GET_DEVICE_TOKEN";
export const GET_NOTIFICATION_SETTING = "GET_NOTIFICATION_SETTING";
export const SET_NOTIFICATION_SETTING = "SET_NOTIFICATION_SETTING";
export const GET_NOTIFICATION_ADMIN_SETTING = "GET_NOTIFICATION_ADMIN_SETTING";
export const GET_REVIEW_FIELDS = "GET_REVIEW_FIELDS";
export const POST_REVIEW = "POST_REVIEW";
export const PUT_REVIEW = "PUT_REVIEW";
export const POST_REVIEW_ERROR = "POST_REVIEW_ERROR";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const LIKE_REVIEW = "LIKE_REVIEW";
export const SHARE_REVIEW = "SHARE_REVIEW";

export const GET_LISTING_RESTAURANT_MENU = "GET_LISTING_RESTAURANT_MENU";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const PRODUCT_TIMEOUT = "PRODUCT_TIMEOUT";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_PRODUCTS_CART = "GET_PRODUCTS_CART";
export const REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const UPDATE_CART_ERR = "UPDATE_CART_ERR";
export const GET_BILLING_FORM = "GET_BILLING_FORM";
export const GET_SHIPPING_FORM = "GET_SHIPPING_FORM";
export const GET_RESULTS_BILLING = "GET_RESULTS_BILLING";
export const GET_RESULTS_SHIPPING = "GET_RESULTS_SHIPPING";
export const GET_METHOD_RESULT = "GET_METHOD_RESULT";
export const UNCHECKED_FORM = "UNCHECKED_FORM";
export const VERIFY_PAYMENT = "VERIFY_PAYMENT";
export const GET_METHOD_PAYMENT = "GET_METHOD_PAYMENT";
export const PAYMENT_TIMEOUT = "PAYMENT_TIMEOUT";
export const GET_ORDER = "GET_ORDER";
export const GET_TEMP_TOKEN = "GET_TEMP_TOKEN";
export const GET_ORDER_ERR = "GET_ORDER_ERR";
export const CHANGE_QUANTITY_2 = "CHANGE_QUANTITY_2";
export const GET_VARIATIONS = "GET_VARIATIONS";
export const SELECTED_ATTRIBUTE = "SELECTED_ATTRIBUTE";
export const RESET_ATTRIBUTE = "RESET_ATTRIBUTE";
export const PRODUCT_CART_TIMEOUT = "PRODUCT_CART_TIMEOUT";
export const GET_RATING_STATICS = "GET_RATING_STATICS";
export const GET_COMMENT_RATING = "GET_COMMENT_RATING";
export const GET_COMMENT_RATING_LOAD_MORE = "GET_COMMENT_RATING_LOAD_MORE";
export const GET_COMMENT_ERR = "GET_COMMENT_ERR";
export const ADD_PRODUCT_FAVORITES = "ADD_PRODUCT_FAVORITES";
export const REMOVE_PRODUCT_FAVORITES = "REMOVE_PRODUCT_FAVORITES";
export const GET_FAVORITES_PRODUCTS = "GET_FAVORITES_PRODUCTS";
export const GET_FAVORITES_LOADMORE = "GET_FAVORITES_LOADMORE";
export const GET_LIST_ORDER = "GET_LIST_ORDER";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const GET_LOADMORE_ORDER = "GET_LOADMORE_ORDER";
export const RESET_ORDER = "RESET_ORDER";
export const CHECK_TYPE_ORDER = "CHECK_TYPE_ORDER";
export const GET_LISTING_PRODUCTS = "GET_LISTING_PRODUCTS";
export const GET_BOOKING_DETAILS = "GET_BOOKING_DETAILS";
export const GET_MORE_BOOKING = "GET_MORE_BOOKING";
export const GET_LIST_BOOKING = "GET_LIST_BOOKING";
export const GET_SUBMENU_DOKAN = "GET_SUBMENU_DOKAN";
export const GET_PRODUCTS_DOKAN = "GET_PRODUCTS_DOKAN";
export const GET_PRODUCTS_DOKAN_LOADMORE = "GET_PRODUCTS_DOKAN_LOADMORE";
export const GET_ORDER_DOKAN = "GET_ORDER_DOKAN";
export const GET_ORDER_DOKAN_LOADMORE = "GET_ORDER_DOKAN_LOADMORE";
export const GET_STATICS_DOKAN = "GET_STATICS_DOKAN";
export const GET_WITHDRAW_DOKAN = "GET_WITHDRAW_DOKAN";
export const GET_STATUS_DRAWN_DOKAN = "GET_STATUS_DRAWN_DOKAN";
export const MAKE_REQUEST_DOKAN = "MAKE_REQUEST_DOKAN";
export const POST_REQUEST_DOKAN = "POST_REQUEST_DOKAN";
export const CANCEL_REQUEST_DOKAN = "CANCEL_REQUEST_DOKAN";
export const GET_TAB_DOKAN = "GET_TAB_DOKAN";
export const UPDATE_TOTAL_REQUESTS = "UPDATE_TOTAL_REQUESTS";
export const RESET_PRODUCT_DETAILS = "RESET_PRODUCT_DETAILS";
export const WISHLIST_TOKEN = "WISHLIST_TOKEN";
export const DEDUCT_TO_CART = "DEDUCT_TO_CART";
export const LOADED_LISTING_DETAILS = "LOADED_LISTING_DETAILS";
export const GET_LISTING_PRODUCTS_ALL = "GET_LISTING_PRODUCTS_ALL";
export const IS_DELETE_ITEM = "IS_DELETE_ITEM";
export const REMOVE_ALL_PRODUCT = "REMOVE_ALL_PRODUCT";
export const SAVE_RESULT_FORM = "SAVE_RESULT_FORM";
export const RESET_MY_LISTING = "RESET_MY_LISTING";
